fix: unset ADMIN variables
This makes the keycloak container fail to start on Keycloak 26 with:

ERROR: Aborting startup and the creation of the master realm, because
the temporary admin user account could not be created

The conflicts comes from the admin user being created on realm import
already.